# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Merc-WithaMouse"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/merc_withamouse"

[social.params]
icon = "brand-twitter"

#[[social]]
#identifier = "reddit"
#name = "Reddit"
#url = "https://reddit.com/u/mercwithamouth420"

#[social.params]
# icon = "brand-reddit"
